from .multi_dict import MultiDict

bone_table_valvebiped = MultiDict({
    ('mixamorig:Hips', 'pelvis',): "ValveBiped.Bip01_Pelvis",
    ('mixamorig:Spine', 'spine',): "ValveBiped.Bip01_Spine1",
    ('mixamorig:Spine1', 'spine1',): "ValveBiped.Bip01_Spine2",
    ('mixamorig:Spine2', 'chest',): "ValveBiped.Bip01_Spine4",
    ('mixamorig:neck', 'neck',): "ValveBiped.Bip01_Neck1",
    ('mixamorig:head', 'head',): "ValveBiped.Bip01_Head1",
    ('mixamorig:LeftShoulder', 'shoulder.l', 'shoulder_l'): "ValveBiped.Bip01_L_Clavicle",
    ('mixamorig:LeftArm', 'upperarm_l', "upperarm.l"): "ValveBiped.Bip01_L_UpperArm",
    ('mixamorig:LeftForearm', 'forearm_l', 'forearm.l'): "ValveBiped.Bip01_L_Forearm",
    ('mixamorig:LeftHand', 'hand_l', 'hand.l'): "ValveBiped.Bip01_L_Hand",
    ('mixamorig:LeftHandThumb1', 'fing.Thumb0.l'): "ValveBiped.Bip01_L_Finger0",
    ('mixamorig:LeftHandThumb2', 'fing.Thumb1.l'): "ValveBiped.Bip01_L_Finger01",
    ('mixamorig:LeftHandThumb3', 'fing.Thumb2.l'): "ValveBiped.Bip01_L_Finger02",
    ('mixamorig:LeftHandIndex1', 'fing.Index0.l'): "ValveBiped.Bip01_L_Finger1",
    ('mixamorig:LeftHandIndex2', 'fing.Index1.l'): "ValveBiped.Bip01_L_Finger11",
    ('mixamorig:LeftHandIndex3', 'fing.Index2.l'): "ValveBiped.Bip01_L_Finger12",
    ('mixamorig:LeftHandMiddle1', 'fing.Middle0.l'): "ValveBiped.Bip01_L_Finger2",
    ('mixamorig:LeftHandMiddle2', 'fing.Middle1.l'): "ValveBiped.Bip01_L_Finger21",
    ('mixamorig:LeftHandMiddle3', 'fing.Middle2.l'): "ValveBiped.Bip01_L_Finger22",
    ('mixamorig:LeftHandRing1', 'fing.Ring0.l'): "ValveBiped.Bip01_L_Finger3",
    ('mixamorig:LeftHandRing2', 'fing.Ring1.l'): "ValveBiped.Bip01_L_Finger31",
    ('mixamorig:LeftHandRing3', 'fing.Ring2.l'): "ValveBiped.Bip01_L_Finger32",
    ('mixamorig:LeftHandPinky1', 'fing.Pinky0.l'): "ValveBiped.Bip01_L_Finger4",
    ('mixamorig:LeftHandPinky2', 'fing.Pinky1.l'): "ValveBiped.Bip01_L_Finger41",
    ('mixamorig:LeftHandPinky3', 'fing.Pinky2.l'): "ValveBiped.Bip01_L_Finger42",
    ('mixamorig:RightShoulder', 'shoulder.r', 'shoulder_r'): "ValveBiped.Bip01_R_Clavicle",
    ('mixamorig:RightArm', 'upperarm_r', "upperarm.r"): "ValveBiped.Bip01_R_UpperArm",
    ('mixamorig:RightForearm', 'forearm_r', 'forearm.r'): "ValveBiped.Bip01_R_Forearm",
    ('mixamorig:RightHand', 'hand_r', 'hand.r'): "ValveBiped.Bip01_R_Hand",
    ('mixamorig:RightHandThumb1', 'fing.Thumb0.r'): "ValveBiped.Bip01_R_Finger0",
    ('mixamorig:RightHandThumb2', 'fing.Thumb1.r'): "ValveBiped.Bip01_R_Finger01",
    ('mixamorig:RightHandThumb3', 'fing.Thumb2.r'): "ValveBiped.Bip01_R_Finger02",
    ('mixamorig:RightHandIndex1', 'fing.Index0.r'): "ValveBiped.Bip01_R_Finger1",
    ('mixamorig:RightHandIndex2', 'fing.Index1.r'): "ValveBiped.Bip01_R_Finger11",
    ('mixamorig:RightHandIndex3', 'fing.Index2.r'): "ValveBiped.Bip01_R_Finger12",
    ('mixamorig:RightHandMiddle1', 'fing.Middle0.r'): "ValveBiped.Bip01_R_Finger2",
    ('mixamorig:RightHandMiddle2', 'fing.Middle1.r'): "ValveBiped.Bip01_R_Finger21",
    ('mixamorig:RightHandMiddle3', 'fing.Middle2.r'): "ValveBiped.Bip01_R_Finger22",
    ('mixamorig:RightHandRing1', 'fing.Ring0.r'): "ValveBiped.Bip01_R_Finger3",
    ('mixamorig:RightHandRing2', 'fing.Ring1.r'): "ValveBiped.Bip01_R_Finger31",
    ('mixamorig:RightHandRing3', 'fing.Ring2.r'): "ValveBiped.Bip01_R_Finger32",
    ('mixamorig:RightHandPinky1', 'fing.Pinky0.r'): "ValveBiped.Bip01_R_Finger4",
    ('mixamorig:RightHandPinky2', 'fing.Pinky1.r'): "ValveBiped.Bip01_R_Finger41",
    ('mixamorig:RightHandPinky3', 'fing.Pinky2.r'): "ValveBiped.Bip01_R_Finger42",
    ('mixamorig:LeftUpLeg', 'hip_l', 'hip.l'): "ValveBiped.Bip01_L_Thigh",
    ('mixamorig:LeftLeg', 'knee_l', 'knee.l'): "ValveBiped.Bip01_L_Calf",
    ('mixamorig:LeftFoot', 'foot_l', 'foot.l'): "ValveBiped.Bip01_L_Foot",
    ('mixamorig:LeftToeBase', 'toe_l', 'toe.l'): "ValveBiped.Bip01_L_Toe0",
    ('mixamorig:RightUpLeg', 'hip_r', 'hip.r'): "ValveBiped.Bip01_R_Thigh",
    ('mixamorig:RightLeg', 'knee_r', 'knee.r'): "ValveBiped.Bip01_R_Calf",
    ('mixamorig:RightFoot', 'foot_r', 'foot.r'): "ValveBiped.Bip01_R_Foot",
    ('mixamorig:RightToeBase', 'toe_r', 'toe.r'): "ValveBiped.Bip01_R_Toe0",
})
bone_table_bip = MultiDict({
    ('mixamorig:Hips', 'pelvis', "ValveBiped.Bip01_Pelvis"): "bip_pelvis",
    ('mixamorig:Spine', 'spine', "ValveBiped.Bip01_Spine1"): "bip_spine_0",
    ('mixamorig:Spine1', 'spine1', "ValveBiped.Bip01_Spine2"): "bip_spine_1",
    ('spine2', "ValveBiped.Bip01_Spine4"): "bip_spine_2",
    ('mixamorig:Spine2', 'chest',): "bip_spine_3",
    ('mixamorig:neck', 'neck', "ValveBiped.Bip01_Neck1"): "bip_neck",
    ('mixamorig:head', 'head', "ValveBiped.Bip01_Head1"): "bip_head",
    ('mixamorig:LeftShoulder', 'shoulder.l', 'shoulder_l', "ValveBiped.Bip01_L_Clavicle"): "bip_collar_L",
    ('mixamorig:LeftArm', 'upperarm_l', "upperarm.l", "ValveBiped.Bip01_L_UpperArm"): "bip_upperArm_L",
    ('mixamorig:LeftForearm', 'forearm_l', 'forearm.l', "ValveBiped.Bip01_L_Forearm"): "bip_lowerArm_L",
    ('mixamorig:LeftHand', 'hand_l', 'hand.l',"ValveBiped.Bip01_L_Hand"): "bip_hand_L",
    ('mixamorig:LeftHandThumb1', 'fing.Thumb0.l',"ValveBiped.Bip01_L_Finger0",  ): "bip_thumb_0_L",
    ('mixamorig:LeftHandThumb2', 'fing.Thumb1.l',"ValveBiped.Bip01_L_Finger01", ): "bip_thumb_1_L",
    ('mixamorig:LeftHandThumb3', 'fing.Thumb2.l',"ValveBiped.Bip01_L_Finger02", ): "bip_thumb_2_L",
    ('mixamorig:LeftHandIndex1', 'fing.Index0.l',"ValveBiped.Bip01_L_Finger1",  ): "bip_index_0_L",
    ('mixamorig:LeftHandIndex2', 'fing.Index1.l',"ValveBiped.Bip01_L_Finger11", ): "bip_index_1_L",
    ('mixamorig:LeftHandIndex3', 'fing.Index2.l',"ValveBiped.Bip01_L_Finger12", ): "bip_index_2_L",
    ('mixamorig:LeftHandMiddle1', 'fing.Middle0.l',"ValveBiped.Bip01_L_Finger2", ): "bip_middle_0_L",
    ('mixamorig:LeftHandMiddle2', 'fing.Middle1.l',"ValveBiped.Bip01_L_Finger21",): "bip_middle_1_L",
    ('mixamorig:LeftHandMiddle3', 'fing.Middle2.l',"ValveBiped.Bip01_L_Finger22",): "bip_middle_2_L",
    ('mixamorig:LeftHandRing1', 'fing.Ring0.l',"ValveBiped.Bip01_L_Finger3",): "bip_ring_0_L",
    ('mixamorig:LeftHandRing2', 'fing.Ring1.l',"ValveBiped.Bip01_L_Finger31",): "bip_ring_1_L",
    ('mixamorig:LeftHandRing3', 'fing.Ring2.l',"ValveBiped.Bip01_L_Finger32",): "bip_ring_2_L",
    ('mixamorig:LeftHandPinky1', 'fing.Pinky0.l',"ValveBiped.Bip01_L_Finger4",): "bip_pinky_0_L",
    ('mixamorig:LeftHandPinky2', 'fing.Pinky1.l',"ValveBiped.Bip01_L_Finger41",): "bip_pinky_1_L",
    ('mixamorig:LeftHandPinky3', 'fing.Pinky2.l',"ValveBiped.Bip01_L_Finger42",): "bip_pinky_2_L",
    ('mixamorig:RightShoulder', 'shoulder.r', 'shoulder_r',"ValveBiped.Bip01_R_Clavicle",): "bip_collar_R",
    ('mixamorig:RightArm', 'upperarm_r', "upperarm.r","ValveBiped.Bip01_R_UpperArm",): "bip_upperArm_R",
    ('mixamorig:RightForearm', 'forearm_r', 'forearm.r',"ValveBiped.Bip01_R_Forearm",): "bip_lowerArm_R",
    ('mixamorig:RightHand', 'hand_r', 'hand.r',"ValveBiped.Bip01_R_Hand",): "bip_hand_R",
    ('mixamorig:RightHandThumb1', 'fing.Thumb0.r',"ValveBiped.Bip01_R_Finger0",): "bip_thumb_0_R",
    ('mixamorig:RightHandThumb2', 'fing.Thumb1.r',"ValveBiped.Bip01_R_Finger01",): "bip_thumb_1_R",
    ('mixamorig:RightHandThumb3', 'fing.Thumb2.r',"ValveBiped.Bip01_R_Finger02",): "bip_thumb_2_R",
    ('mixamorig:RightHandIndex1', 'fing.Index0.r',"ValveBiped.Bip01_R_Finger1",): "bip_index_0_R",
    ('mixamorig:RightHandIndex2', 'fing.Index1.r',"ValveBiped.Bip01_R_Finger11",): "bip_index_1_R",
    ('mixamorig:RightHandIndex3', 'fing.Index2.r',"ValveBiped.Bip01_R_Finger12",): "bip_index_2_R",
    ('mixamorig:RightHandMiddle1', 'fing.Middle0.r',"ValveBiped.Bip01_R_Finger2",): "bip_middle_0_R",
    ('mixamorig:RightHandMiddle2', 'fing.Middle1.r',"ValveBiped.Bip01_R_Finger21",): "bip_middle_1_R",
    ('mixamorig:RightHandMiddle3', 'fing.Middle2.r',"ValveBiped.Bip01_R_Finger22",): "bip_middle_2_R",
    ('mixamorig:RightHandRing1', 'fing.Ring0.r',"ValveBiped.Bip01_R_Finger3",): "bip_ring_0_R",
    ('mixamorig:RightHandRing2', 'fing.Ring1.r',"ValveBiped.Bip01_R_Finger31",): "bip_ring_1_R",
    ('mixamorig:RightHandRing3', 'fing.Ring2.r',"ValveBiped.Bip01_R_Finger32",): "bip_ring_2_R",
    ('mixamorig:RightHandPinky1', 'fing.Pinky0.r',"ValveBiped.Bip01_R_Finger4",): "bip_pinky_0_R",
    ('mixamorig:RightHandPinky2', 'fing.Pinky1.r',"ValveBiped.Bip01_R_Finger41",): "bip_pinky_1_R",
    ('mixamorig:RightHandPinky3', 'fing.Pinky2.r',"ValveBiped.Bip01_R_Finger42",): "bip_pinky_2_R",
    ('mixamorig:LeftUpLeg', 'hip_l', 'hip.l',"ValveBiped.Bip01_L_Thigh",): "bip_hip_L",
    ('mixamorig:LeftLeg', 'knee_l', 'knee.l',"ValveBiped.Bip01_L_Calf",): "bip_knee_L",
    ('mixamorig:LeftFoot', 'foot_l', 'foot.l',"ValveBiped.Bip01_L_Foot",): "bip_foot_L",
    ('mixamorig:LeftToeBase', 'toe_l', 'toe.l', "ValveBiped.Bip01_L_Toe0",): "bip_toe_L",
    ('mixamorig:RightUpLeg', 'hip_r', 'hip.r',"ValveBiped.Bip01_R_Thigh",): "bip_hip_R",
    ('mixamorig:RightLeg', 'knee_r', 'knee.r',"ValveBiped.Bip01_R_Calf",): "bip_knee_R",
    ('mixamorig:RightFoot', 'foot_r', 'foot.r',"ValveBiped.Bip01_R_Foot",): "bip_foot_R",
    ('mixamorig:RightToeBase', 'toe_r', 'toe.r', "ValveBiped.Bip01_R_Toe0",): "bip_toe_R",
})
