bones_aponia = {
    'Bone_Aponia_C1_Ribbon_B1_01',
    'Bone_Aponia_C1_Ribbon_B1_End',

    'Bone_Aponia_C1_Hair_FR_01',
    'Bone_Aponia_C1_Hair_FR_02',
    'Bone_Aponia_C1_Hair_FR_03',
    'Bone_Aponia_C1_Hair_FR_04',
    'Bone_Aponia_C1_Hair_FR_End',

    'Bone_Aponia_C1_Hair_FL_01',
    'Bone_Aponia_C1_Hair_FL_02',
    'Bone_Aponia_C1_Hair_FL_03',
    'Bone_Aponia_C1_Hair_FL_04',
    'Bone_Aponia_C1_Hair_FL_End',

    'Bone_Aponia_C1_Hair_B_01',
    'Bone_Aponia_C1_Hair_B_02',
    'Bone_Aponia_C1_Hair_B_03',
    'Bone_Aponia_C1_Hair_B_04',
    'Bone_Aponia_C1_Hair_B_End',

    'Bone_Aponia_C1_Hair_FL1_01',
    'Bone_Aponia_C1_Hair_FL1_02',
    'Bone_Aponia_C1_Hair_FL1_End',

    'Bone_Aponia_C1_Hair_FR1_01',
    'Bone_Aponia_C1_Hair_FR1_02',
    'Bone_Aponia_C1_Hair_FR1_End',

    'Bone_Aponia_C1_Bow_FR_01',
    'Bone_Aponia_C1_Bow_FR_02',
    'Bone_Aponia_C1_Bow_FR_End',

    'Bone_Aponia_C1_Bow_FL_01',
    'Bone_Aponia_C1_Bow_FL_02',
    'Bone_Aponia_C1_Bow_FL_End',

    'Bone_Aponia_C1_Ribbon_FR_01',
    'Bone_Aponia_C1_Ribbon_FR_02',
    'Bone_Aponia_C1_Ribbon_FR_03',
    'Bone_Aponia_C1_Ribbon_FR_04',
    'Bone_Aponia_C1_Ribbon_FR_05',
    'Bone_Aponia_C1_Ribbon_FR_End',

    'Bone_Aponia_C1_Ribbon_FL_01',
    'Bone_Aponia_C1_Ribbon_FL_02',
    'Bone_Aponia_C1_Ribbon_FL_03',
    'Bone_Aponia_C1_Ribbon_FL_04',
    'Bone_Aponia_C1_Ribbon_FL_05',
    'Bone_Aponia_C1_Ribbon_FL_End',

    'Bone_Aponia_C1_Ribbon_BL_01',
    'Bone_Aponia_C1_Ribbon_BL_02',
    'Bone_Aponia_C1_Ribbon_BL_03',
    'Bone_Aponia_C1_Ribbon_BL_04',
    'Bone_Aponia_C1_Ribbon_BL_End',

    'Bone_Aponia_C1_Ribbon_BR_01',
    'Bone_Aponia_C1_Ribbon_BR_02',
    'Bone_Aponia_C1_Ribbon_BR_03',
    'Bone_Aponia_C1_Ribbon_BR_04',
    'Bone_Aponia_C1_Ribbon_BR_End',

    'Bone_Aponia_C1_Wing_BL1_01',
    'Bone_Aponia_C1_Wing_BL1_02',
    'Bone_Aponia_C1_Wing_BL1_03',
    'Bone_Aponia_C1_Wing_BL1_04',
    'Bone_Aponia_C1_Wing_BL1_05',
    'Bone_Aponia_C1_Wing_BL1_06',
    'Bone_Aponia_C1_Wing_BL1_End',

    'Bone_Aponia_C1_Wing_BL2_01',
    'Bone_Aponia_C1_Wing_BL2_02',
    'Bone_Aponia_C1_Wing_BL2_03',
    'Bone_Aponia_C1_Wing_BL2_04',
    'Bone_Aponia_C1_Wing_BL2_05',
    'Bone_Aponia_C1_Wing_BL2_06',
    'Bone_Aponia_C1_Wing_BL2_End',

    'Bone_Aponia_C1_Wing_BR2_01',
    'Bone_Aponia_C1_Wing_BR2_02',
    'Bone_Aponia_C1_Wing_BR2_03',
    'Bone_Aponia_C1_Wing_BR2_04',
    'Bone_Aponia_C1_Wing_BR2_05',
    'Bone_Aponia_C1_Wing_BR2_06',
    'Bone_Aponia_C1_Wing_BR2_End',

    'Bone_Aponia_C1_Wing_BR1_01',
    'Bone_Aponia_C1_Wing_BR1_02',
    'Bone_Aponia_C1_Wing_BR1_03',
    'Bone_Aponia_C1_Wing_BR1_04',
    'Bone_Aponia_C1_Wing_BR1_05',
    'Bone_Aponia_C1_Wing_BR1_06',
    'Bone_Aponia_C1_Wing_BR1_End',

    'Bone_Aponia_C1_Wing1_BL1_01',
    'Bone_Aponia_C1_Wing1_BL1_02',
    'Bone_Aponia_C1_Wing1_BL1_03',
    'Bone_Aponia_C1_Wing1_BL1_04',
    'Bone_Aponia_C1_Wing1_BL1_05',
    'Bone_Aponia_C1_Wing1_BL1_06',
    'Bone_Aponia_C1_Wing1_BL1_End',

    'Bone_Aponia_C1_Wing1_BR1_01',
    'Bone_Aponia_C1_Wing1_BR1_02',
    'Bone_Aponia_C1_Wing1_BR1_03',
    'Bone_Aponia_C1_Wing1_BR1_04',
    'Bone_Aponia_C1_Wing1_BR1_05',
    'Bone_Aponia_C1_Wing1_BR1_06',
    'Bone_Aponia_C1_Wing1_BR1_End',

    'Bone_Aponia_C1_Wing1_BR2_01',
    'Bone_Aponia_C1_Wing1_BR2_02',
    'Bone_Aponia_C1_Wing1_BR2_03',
    'Bone_Aponia_C1_Wing1_BR2_04',
    'Bone_Aponia_C1_Wing1_BR2_End',

    'Bone_Aponia_C1_Wing1_BR3_01',
    'Bone_Aponia_C1_Wing1_BR3_02',
    'Bone_Aponia_C1_Wing1_BR3_03',
    'Bone_Aponia_C1_Wing1_BR3_04',
    'Bone_Aponia_C1_Wing1_BR3_05',
    'Bone_Aponia_C1_Wing1_BR3_End',

    'Bone_Aponia_C1_Wing1_BL2_01',
    'Bone_Aponia_C1_Wing1_BL2_02',
    'Bone_Aponia_C1_Wing1_BL2_03',
    'Bone_Aponia_C1_Wing1_BL2_04',
    'Bone_Aponia_C1_Wing1_BL2_End',

    'Bone_Aponia_C1_Wing1_BL3_01',
    'Bone_Aponia_C1_Wing1_BL3_02',
    'Bone_Aponia_C1_Wing1_BL3_03',
    'Bone_Aponia_C1_Wing1_BL3_04',
    'Bone_Aponia_C1_Wing1_BL3_05',
    'Bone_Aponia_C1_Wing1_BL3_End',

}
bone_aponia_tip = {  # appear at same layer as bones_aponia and layer 31
    'Bone_Aponia_C1_Ribbon_B1_End',
    'Bone_Aponia_C1_Hair_FR_End',
    'Bone_Aponia_C1_Hair_FL_End',
    'Bone_Aponia_C1_Hair_B_End',
    'Bone_Aponia_C1_Hair_FL1_End',
    'Bone_Aponia_C1_Hair_FR1_End',
    'Bone_Aponia_C1_Bow_FR_End',
    'Bone_Aponia_C1_Bow_FL_End',
    'Bone_Aponia_C1_Ribbon_FR_End',
    'Bone_Aponia_C1_Ribbon_FL_End',
    'Bone_Aponia_C1_Ribbon_BL_End',
    'Bone_Aponia_C1_Ribbon_BR_End',
    'Bone_Aponia_C1_Wing_BL1_End',
    'Bone_Aponia_C1_Wing_BL2_End',
    'Bone_Aponia_C1_Wing_BR2_End',
    'Bone_Aponia_C1_Wing_BR1_End',
    'Bone_Aponia_C1_Wing1_BL1_End',
    'Bone_Aponia_C1_Wing1_BR1_End',
    'Bone_Aponia_C1_Wing1_BR2_End',
    'Bone_Aponia_C1_Wing1_BR3_End',
    'Bone_Aponia_C1_Wing1_BL2_End',
    'Bone_Aponia_C1_Wing1_BL3_End',

}
aponia_lingering = {  # layer 3
    '头巾_0_1_L',
    '头巾_1_1_L',
    '头巾_2_1_L',
    '头巾_3_1_L',
    '头巾_4_1_L',
    '头巾_5_1_L',
    '头巾_6_1_L',
    '头巾_7_1_L',
    '头巾_8_1_L',
    '头巾_9_1_L',
    '头巾_10_1_L',
    '头巾_11_1_L',
    '头巾_12_1_L',
    '头巾_13_1_L',
    '头巾_14_1_L',
    '头巾_0_1_R',
    '头巾_1_1_R',
    '头巾_2_1_R',
    '头巾_3_1_R',
    '头巾_4_1_R',
    '头巾_5_1_R',
    '头巾_6_1_R',
    '头巾_7_1_R',
    '头巾_8_1_R',
    '头巾_9_1_R',
    '头巾_10_1_R',
    '头巾_11_1_R',
    '头巾_12_1_R',
    '头巾_13_1_R',
    '头巾_14_1_R',
}
