bones = {  # uses layer 0
    'Hip',        #
    'Spine',      # Case Renamed
    'Spine0',     # Case Renamed
    'Spine1',     # Case Renamed
    'Spine2',     # Case Renamed
    'Spine3',     # Case Renamed
    'Spine4',     # Case Renamed
    'Waist',      # Pelvis
    'LowerBody',  # Spine
    'UpperBody',  # Spine1
    'UpperBody2',  # Spine4
    'Leg_R',      #
    'Knee_R',     #
    'Ankle_R',    #
    'Leg_L',      #
    'Knee_L',     #
    'Ankle_L',    #
    'Neck',       # Case Renamed
    'Neck1',      # Case Renamed
    'Head',       # Case Renamed
    'Head1',
    'LegD_R',
    'LegD_L',
    'LeftLegD',
    'RightLegD',
    'KneeD_R',
    'KneeD_L',
    'RightKneeD',
    'LeftKneeD',
    'AnkleD_R',
    'AnkleD_L',
    'RightAnkleD',
    'LeftAnkleD',
    'LegTipEX_R',
    'LegTipEX_L',
    'RightLegTipEX',
    'LeftLegTipEX',
    'Clavicle_R',
    'Clavicle_L',
    'Right_shoulder',
    'Left_shoulder',
    'Right shoulder',
    'Left shoulder',
    'Rightshoulder',
    'Leftshoulder',
    'Arm_R',
    'Arm_L',
    'Right_arm',
    'Left_arm',
    'Right arm',
    'Left arm',
    'Rightarm',
    'Leftarm',
    'Elbow_R',
    'Elbow_L',
    'Right_elbow',
    'Left_elbow',
    'Right elbow',
    'Left elbow',
    'Rightelbow',
    'Leftelbow',
    'Wrists_R',
    'Wrists_L',
    'Right wrist',
    'Left wrist',
    'Rightwrist',
    'Leftwrist',
    'Right_wrist',
    'Left_wrist',
    'Thumb0_R',
    'Thumb0_L',
    'Thumb1_R',
    'Thumb1_L',
    'Thumb2_R',
    'Thumb2_L',
    'IndexFinger1_R',
    'IndexFinger1_L',
    'IndexFinger2_R',
    'IndexFinger2_L',
    'IndexFinger3_R',
    'IndexFinger3_L',
    'MiddleFinger1_R',
    'MiddleFinger1_L',
    'MiddleFinger2_R',
    'MiddleFinger2_L',
    'MiddleFinger3_R',
    'MiddleFinger3_L',
    'RingFinger1_R',
    'RingFinger1_L',
    'RingFinger2_R',
    'RingFinger2_L',
    'RingFinger3_R',
    'RingFinger3_L',
    'LittleFinger1_R',
    'LittleFinger1_L',
    'LittleFinger2_R',
    'LittleFinger2_L',
    'LittleFinger3_R',
    'LittleFinger3_L',
    'RightThumb0',
    'LeftThumb0',
    'RightThumb1',
    'LeftThumb1',
    'RightThumb2',
    'LeftThumb2',
    'RightIndexFinger1',
    'LeftIndexFinger1',
    'RightIndexFinger2',
    'LeftIndexFinger2',
    'RightIndexFinger3',
    'LeftIndexFinger3',
    'RightMiddleFinger1',
    'LeftMiddleFinger1',
    'RightMiddleFinger2',
    'LeftMiddleFinger2',
    'RightMiddleFinger3',
    'LeftMiddleFinger3',
    'RightRingFinger1',
    'LeftRingFinger1',
    'RightRingFinger2',
    'LeftRingFinger2',
    'RightRingFinger3',
    'LeftRingFinger3',
    'RightLittleFinger1',
    'LeftLittleFinger1',
    'RightLittleFinger2',
    'LeftLittleFinger2',
    'RightLittleFinger3',
    'LeftLittleFinger3',
}
