
# Purpose: select an armature on a human model imported form Left 4 Dead, Garry's Mode, Half-Life 2
# run this script, all bones renamed to their Blender counterparts

names = dict()

# Purpose: select an armature from a ValveBiped model
# run this
# Get a Blender style armature

names['Pelvis'] = 'ValveBiped.Bip01_Pelvis'
names['Spine'] = 'ValveBiped.Bip01_Spine'
names['Spine0'] = 'ValveBiped.Bip01_Spine0'
names['Spine1'] = 'ValveBiped.Bip01_Spine1'
names['Spine2'] = 'ValveBiped.Bip01_Spine2'
names['Spine3'] = 'ValveBiped.Bip01_Spine3'
names['Spine4'] = 'ValveBiped.Bip01_Spine4'

names['Neck1'] = 'ValveBiped.Bip01_Neck1'
names['Head1'] = 'ValveBiped.Bip01_Head1'

names['Hip_R'] = 'ValveBiped.Bip01_R_Hip'
names['Hip_L'] = 'ValveBiped.Bip01_L_Hip'
names['Glute_R'] = 'ValveBiped.Bip01_R_Glute'
names['Glute_L'] = 'ValveBiped.Bip01_L_Glute'
names['Sartorius_R'] = 'ValveBiped.Bip01_R_Sartorius'
names['Sartorius_L'] = 'ValveBiped.Bip01_L_Sartorius'
names['Thigh_R'] = 'ValveBiped.Bip01_R_Thigh'
names['Thigh_L'] = 'ValveBiped.Bip01_L_Thigh'
names['Quadricep_R'] = 'ValveBiped.Bip01_R_Quadricep'
names['Quadricep_L'] = 'ValveBiped.Bip01_L_Quadricep'
names['Quad_R'] = 'ValveBiped.Bip01_R_Quad'
names['Quad_L'] = 'ValveBiped.Bip01_L_Quad'
names['Knee_R'] = 'ValveBiped.Bip01_R_Knee'
names['Knee_L'] = 'ValveBiped.Bip01_L_Knee'
names['Calf_R'] = 'ValveBiped.Bip01_R_Calf'
names['Calf_L'] = 'ValveBiped.Bip01_L_Calf'
names['Shin_R'] = 'ValveBiped.Bip01_R_Shin'
names['Shin_L'] = 'ValveBiped.Bip01_L_Shin'
names['Soleus_R'] = 'ValveBiped.Bip01_R_Soleus'
names['Soleus_L'] = 'ValveBiped.Bip01_L_Soleus'
names['Ankle_R'] = 'ValveBiped.Bip01_R_Ankle'
names['Ankle_L'] = 'ValveBiped.Bip01_L_Ankle'
names['Foot_R'] = 'ValveBiped.Bip01_R_Foot'
names['Foot_L'] = 'ValveBiped.Bip01_L_Foot'
names['Toe0_R'] = 'ValveBiped.Bip01_R_Toe0'
names['Toe0_L'] = 'ValveBiped.Bip01_L_Toe0'

names['Pectoral_R'] = 'ValveBiped.Bip01_R_Pectoral'
names['Pectoral_L'] = 'ValveBiped.Bip01_L_Pectoral'
names['Latt_R'] = 'ValveBiped.Bip01_R_Latt'
names['Latt_L'] = 'ValveBiped.Bip01_L_Latt'
names['Trapezius_R'] = 'ValveBiped.Bip01_R_Trapezius'
names['Trapezius_L'] = 'ValveBiped.Bip01_L_Trapezius'
names['Clavicle_R'] = 'ValveBiped.Bip01_R_Clavicle'
names['Clavicle_L'] = 'ValveBiped.Bip01_L_Clavicle'
names['Shoulder_R'] = 'ValveBiped.Bip01_R_Shoulder'
names['Shoulder_L'] = 'ValveBiped.Bip01_L_Shoulder'
names['Bicep_R'] = 'ValveBiped.Bip01_R_Bicep'
names['Bicep_L'] = 'ValveBiped.Bip01_L_Bicep'
names['UpperArm_R'] = 'ValveBiped.Bip01_R_UpperArm'
names['UpperArm_L'] = 'ValveBiped.Bip01_L_UpperArm'
names['Elbow_R'] = 'ValveBiped.Bip01_R_Elbow'
names['Elbow_L'] = 'ValveBiped.Bip01_L_Elbow'
names['Forearm_R'] = 'ValveBiped.Bip01_R_Forearm'
names['Forearm_L'] = 'ValveBiped.Bip01_L_Forearm'
names['Ulna_R'] = 'ValveBiped.Bip01_R_Ulna'
names['Ulna_L'] = 'ValveBiped.Bip01_L_Ulna'
names['Wrist_R'] = 'ValveBiped.Bip01_R_Wrist'
names['Wrist_L'] = 'ValveBiped.Bip01_L_Wrist'
names['Hand_R'] = 'ValveBiped.Bip01_R_Hand'
names['Hand_L'] = 'ValveBiped.Bip01_L_Hand'

names['Finger0_R'] = 'ValveBiped.Bip01_R_Finger0'
names['Finger0_L'] = 'ValveBiped.Bip01_L_Finger0'
names['Finger01_R'] = 'ValveBiped.Bip01_R_Finger01'
names['Finger01_L'] = 'ValveBiped.Bip01_L_Finger01'
names['Finger02_R'] = 'ValveBiped.Bip01_R_Finger02'
names['Finger02_L'] = 'ValveBiped.Bip01_L_Finger02'

names['Finger1_R'] = 'ValveBiped.Bip01_R_Finger1'
names['Finger1_L'] = 'ValveBiped.Bip01_L_Finger1'
names['Finger11_R'] = 'ValveBiped.Bip01_R_Finger11'
names['Finger11_L'] = 'ValveBiped.Bip01_L_Finger11'
names['Finger12_R'] = 'ValveBiped.Bip01_R_Finger12'
names['Finger12_L'] = 'ValveBiped.Bip01_L_Finger12'

names['Finger2_R'] = 'ValveBiped.Bip01_R_Finger2'
names['Finger2_L'] = 'ValveBiped.Bip01_L_Finger2'
names['Finger21_R'] = 'ValveBiped.Bip01_R_Finger21'
names['Finger21_L'] = 'ValveBiped.Bip01_L_Finger21'
names['Finger22_R'] = 'ValveBiped.Bip01_R_Finger22'
names['Finger22_L'] = 'ValveBiped.Bip01_L_Finger22'

names['Finger3_R'] = 'ValveBiped.Bip01_R_Finger3'
names['Finger3_L'] = 'ValveBiped.Bip01_L_Finger3'
names['Finger31_R'] = 'ValveBiped.Bip01_R_Finger31'
names['Finger31_L'] = 'ValveBiped.Bip01_L_Finger31'
names['Finger32_R'] = 'ValveBiped.Bip01_R_Finger32'
names['Finger32_L'] = 'ValveBiped.Bip01_L_Finger32'

names['Finger4_R'] = 'ValveBiped.Bip01_R_Finger4'
names['Finger4_L'] = 'ValveBiped.Bip01_L_Finger4'
names['Finger41_R'] = 'ValveBiped.Bip01_R_Finger41'
names['Finger41_L'] = 'ValveBiped.Bip01_L_Finger41'
names['Finger42_R'] = 'ValveBiped.Bip01_R_Finger42'
names['Finger42_L'] = 'ValveBiped.Bip01_L_Finger42'

names['weapon_bone_L'] = 'weapon_bone_L'
names['weapon_bone'] = 'weapon_bone_R'

