################################################################################
# Purpose:
#   Rename Bones (Cyber Sleuth) to Blender's Defaults
#
# Usage:
#	Select an armature imported form Digimon Story: CyberSleuth: Complete Edition.
#	Run this script, all bones renamed to their ValveBiped counterparts
################################################################################

names = dict()

# Tronco
names['j_root']    = 'root'
names['j_center']  = 'Pelvis'
names['j_spine']   = 'Spine'
names['j_spine1']  = 'Spine1'
names['j_spine01'] = 'Spine1'
names['j_spine02'] = 'Spine2'
names['j_spine2']  = 'Spine2'
names['j_spine03'] = 'Spine3'
names['j_spine3']  = 'Spine3'
names['j_spine04'] = 'Spine4'
names['j_spine4']  = 'Spine4'
names['j_neck']    = 'Neck1'
names['j_head']    = 'Head1'

# Braços
names['j_l_collar']    = 'Clavicle_L'
names['j_collar_l']    = 'Clavicle_L'
names['j_clavicle_l']  = 'Clavicle_L'
names['j_shoulder_l']  = 'Clavicle_L'
names['j_r_collar']    = 'Clavicle_R'
names['j_collar_r']    = 'Clavicle_R'
names['j_clavicle_r']  = 'Clavicle_R'
names['j_shoulder_r']  = 'Clavicle_R'
names['j_l_arm']       = 'UpperArm_L'
names['j_arm_l']       = 'UpperArm_L'
names['j_shoulderL']   = 'UpperArm_L'
names['j_r_arm']       = 'UpperArm_R'
names['j_arm_r']       = 'UpperArm_R'
names['j_shoulderR']   = 'UpperArm_R'
names['j_l_elbow']     = 'Forearm_L'
names['j_elbow_l']     = 'Forearm_L'
names['j_elbowL']      = 'Forearm_L'
names['j_erbow_l']     = 'Forearm_L'
names['j_r_elbow']     = 'Forearm_R'
names['j_elbow_r']     = 'Forearm_R'
names['j_elbowR']      = 'Forearm_R'
names['j_erbow_r']     = 'Forearm_R'
names['j_l_hand']      = 'Hand_L'
names['j_hand_l']      = 'Hand_L'
names['j_wristL']      = 'Hand_L'
names['j_r_hand']      = 'Hand_R'
names['j_hand_r']      = 'Hand_R'
names['j_wristR']      = 'Hand_R'
 
# Dedos
names['j_r_thumb01']   = 'Finger0_R'
names['j_l_thumb01']   = 'Finger0_L'
names['j_l_thumb02']   = 'Finger01_L'
names['j_r_thumb02']   = 'Finger01_R'
names['j_l_thumb03']   = 'Finger02_L'
names['j_r_thumb03']   = 'Finger02_R'
names['j_l_index01']   = 'Finger1_L'
names['j_r_index01']   = 'Finger1_R'
names['j_l_index02']   = 'Finger11_L'
names['j_r_index02']   = 'Finger11_R'
names['j_l_index03']   = 'Finger12_L'
names['j_r_index03']   = 'Finger12_R'
names['j_l_middle01']  = 'Finger2_L'
names['j_r_middle01']  = 'Finger2_R'
names['j_l_middle02']  = 'Finger21_L'
names['j_r_middle02']  = 'Finger21_R'
names['j_l_middle03']  = 'Finger22_L'
names['j_r_middle03']  = 'Finger22_R'
names['j_l_ring01']    = 'Finger3_L'
names['j_r_ring01']    = 'Finger3_R'
names['j_l_ring02']    = 'Finger31_L'
names['j_r_ring02']    = 'Finger31_R'
names['j_l_ring03']    = 'Finger32_L'
names['j_r_ring03']    = 'Finger32_R'
names['j_l_pinky01']   = 'Finger4_L'
names['j_r_pinky01']   = 'Finger4_R'
names['j_l_pinky02']   = 'Finger41_L'
names['j_r_pinky02']   = 'Finger41_R'
names['j_l_pinky03']   = 'Finger42_L'
names['j_r_pinky03']   = 'Finger42_R'
  
names['j_thumb01_l']   = 'Finger0_L'
names['j_thumb01_r']   = 'Finger0_R'
names['j_thumb02_l']   = 'Finger01_L'
names['j_thumb02_r']   = 'Finger01_R'
names['j_thumb03_l']   = 'Finger02_L'
names['j_thumb03_r']   = 'Finger02_R'
names['j_index01_l']   = 'Finger1_L'
names['j_index01_r']   = 'Finger1_R'
names['j_index02_l']   = 'Finger11_L'
names['j_index02_r']   = 'Finger11_R'
names['j_index03_l']   = 'Finger12_L'
names['j_index03_r']   = 'Finger12_R'
names['j_middle01_l']  = 'Finger2_L'
names['j_middle01_r']  = 'Finger2_R'
names['j_middle02_l']  = 'Finger21_L'
names['j_middle02_r']  = 'Finger21_R'
names['j_middle03_l']  = 'Finger22_L'
names['j_middle03_r']  = 'Finger22_R'
names['j_ring01_l']    = 'Finger3_L'
names['j_ring01_r']    = 'Finger3_R'
names['j_ring02_l']    = 'Finger31_L'
names['j_ring02_r']    = 'Finger31_R'
names['j_ring03_l']    = 'Finger32_L'
names['j_ring03_r']    = 'Finger32_R'
names['j_pinky01_l']   = 'Finger4_L'
names['j_pinky01_r']   = 'Finger4_R'
names['j_pinky02_l']   = 'Finger41_L'
names['j_pinky02_r']   = 'Finger41_R'
names['j_pinky03_l']   = 'Finger42_L'
names['j_pinky03_r']   = 'Finger42_R'
  
names['j_fore01_l']    = 'Finger1_L'
names['j_fore01_r']    = 'Finger1_R'
names['j_fore02_l']    = 'Finger11_L'
names['j_fore02_r']    = 'Finger11_R'
names['j_fore03_l']    = 'Finger12_L'
names['j_fore03_r']    = 'Finger12_R'
 
names['j_little01_l']  = 'Finger4_L'
names['j_little01_r']  = 'Finger4_R'
names['j_little02_l']  = 'Finger41_L'
names['j_little02_r']  = 'Finger41_R'
names['j_little03_l']  = 'Finger42_L'
names['j_little03_r']  = 'Finger42_R'

names['j_l_finger0']   = 'Finger0_L'
names['j_r_finger0']   = 'Finger0_R'
names['j_l_finger01']  = 'Finger01_L'
names['j_r_finger01']  = 'Finger01_R'
names['j_l_finger02']  = 'Finger02_L'
names['j_r_finger02']  = 'Finger02_R'
names['j_l_finger1']   = 'Finger1_L'
names['j_r_finger1']   = 'Finger1_R'
names['j_l_finger11']  = 'Finger11_L'
names['j_r_finger11']  = 'Finger11_R'
names['j_l_finger11']  = 'Finger12_L'
names['j_r_finger11']  = 'Finger12_R'
names['j_l_finger2']   = 'Finger2_L'
names['j_r_finger2']   = 'Finger2_R'
names['j_l_finger21']  = 'Finger21_L'
names['j_r_finger21']  = 'Finger21_R'
names['j_l_finger22']  = 'Finger22_L'
names['j_r_finger22']  = 'Finger22_R'
names['j_l_finger3']   = 'Finger3_L'
names['j_r_finger3']   = 'Finger3_R'
names['j_l_finger31']  = 'Finger31_L'
names['j_r_finger31']  = 'Finger31_R'
names['j_l_finger32']  = 'Finger32_L'
names['j_r_finger32']  = 'Finger32_R'
names['j_l_finger4']   = 'Finger4_L'
names['j_r_finger4']   = 'Finger4_R'
names['j_l_finger41']  = 'Finger41_L'
names['j_r_finger41']  = 'Finger41_R'
names['j_l_finger42']  = 'Finger42_L'
names['j_r_finger42']  = 'Finger42_R'

# Pernas
names['j_legL']   = 'Thigh_L'
names['j_legR']   = 'Thigh_R'
names['j_kneeL']  = 'Calf_L'
names['j_kneeR']  = 'Calf_R'
names['j_unkleL'] = 'Foot_L'
names['j_unkleR'] = 'Foot_R'
names['j_toeL']   = 'Tor0_L'
names['j_toeR']   = 'Toe0_R'

names['j_l_leg'] = 'Thigh_L'
names['j_r_leg'] = 'Thigh_R'
names['j_l_knee'] = 'Calf_L'
names['j_r_knee'] = 'Calf_R'
names['j_l_foot'] = 'Foot_L'
names['j_r_foot'] = 'Foot_R'
names['j_l_toe'] = 'Toe0_L'
names['j_r_toe'] = 'Toe0_R'
names['j_l_toenail'] = 'Toenail_L'
names['j_r_toenail'] = 'Toenail_R'

names['j_leg_l'] = 'Thigh_L'
names['j_leg_r'] = 'Thigh_R'
names['j_knee_l'] = 'Calf_L'
names['j_knee_r'] = 'Calf_R'
names['j_foot_l'] = 'Foot_L'
names['j_foot_r'] = 'Foot_R'
names['j_toe_l'] = 'Toe0_L'
names['j_toe_r'] = 'Toe0_R'
names['j_toenail_l'] = 'Toenail_L'
names['j_toenail_r'] = 'Toenail_R'

# Attachments
names['j_forward'] = 'forward'
#names['j_'] = 'Anim_Attachment_LH'
#names['j_'] = 'Anim_Attachment_RH'

# Helpers
#names['j_'] = 'Latt_L'
#names['j_'] = 'Latt_R'
#names['j_'] = 'Trapezius_L'
#names['j_'] = 'Trapezius_R'
#names['j_'] = 'Shoulder_L'
#names['j_'] = 'Shoulder_R'
#names['j_'] = 'Bicep_L'
#names['j_'] = 'Bicep_R'
#names['j_'] = 'Elbow_L'
#names['j_'] = 'Elbow_R'
#names['j_'] = 'Ulna_L'
#names['j_'] = 'Ulna_R'
#names['j_'] = 'Wrist_L'
#names['j_'] = 'Wrist_R'

#names['j_'] = 'Hip_L'
#names['j_'] = 'Hip_R'
#names['j_'] = 'Sartorius_L'
#names['j_'] = 'Sartorius_R'
#names['j_'] = 'Quadriceps_L'
#names['j_'] = 'Quadriceps_R'
#names['j_'] = 'ThighTwist_L'
#names['j_'] = 'ThighTwist_R'
#names['j_'] = 'Knee_L'
#names['j_'] = 'Knee_R'
#names['j_'] = 'Shin_L'
#names['j_'] = 'Shin_R'
#names['j_'] = 'Soleus_L'
#names['j_'] = 'Soleus_R'
#names['j_'] = 'CalfTwist_L'
#names['j_'] = 'CalfTwist_R'
#names['j_'] = 'Ankle_L'
#names['j_'] = 'Ankle_R'
#names['j_'] = 'Thumb_L'
#names['j_'] = 'Thumb_R'
#names['j_'] = 'Index_L'
#names['j_'] = 'Index_R'
#names['j_'] = 'Middle_L'
#names['j_'] = 'Middle_R'
#names['j_'] = 'Ring_L'
#names['j_'] = 'Ring_R'
#names['j_'] = 'Pinky_L'
#names['j_'] = 'Pinky_R'

#names['j_'] = 'Toe01_L'
#names['j_'] = 'Toe01_R'
#names['j_'] = 'Toe02_L'
#names['j_'] = 'Toe02_R'
#names['j_'] = 'Toe1_L'
#names['j_'] = 'Toe1_R'
#names['j_'] = 'Toe11_L'
#names['j_'] = 'Toe11_R'
#names['j_'] = 'Toe12_L'
#names['j_'] = 'Toe12_R'
#names['j_'] = 'Toe2_L'
#names['j_'] = 'Toe2_R'
#names['j_'] = 'Toe21_L'
#names['j_'] = 'Toe21_R'
#names['j_'] = 'Toe22_L'
#names['j_'] = 'Toe22_R'
#names['j_'] = 'Toe3_L'
#names['j_'] = 'Toe3_R'
#names['j_'] = 'Toe31_L'
#names['j_'] = 'Toe31_R'
#names['j_'] = 'Toe32_L'
#names['j_'] = 'Toe32_R'
#names['j_'] = 'Toe4_L'
#names['j_'] = 'Toe4_R'
#names['j_'] = 'Toe41_L'
#names['j_'] = 'Toe41_R'
#names['j_'] = 'Toe42_L'
#names['j_'] = 'Toe42_R'

names['j_l_feather']    = 'Feather_L'
names['j_r_feather']    = 'Feather_R'
names['j_l_armor']      = 'Armor_L'
names['j_r_armor']      = 'Armor_R'
names['j_armor_root_l'] = 'Armor_L'
names['j_armor_root_r'] = 'Armor_R'

names['j_ornamentL'] = 'ShoulderPads_L'
names['j_ornamentR'] = 'ShoulderPads_R'

names['j_horn_l'] = 'Horn_L'
names['j_horn_r'] = 'Horn_R'

# Roupas
names['j_fabricF1']  = 'FabricF01'
names['j_fabricF2']  = 'FabricF02'
names['j_fabricF3']  = 'FabricF03'

names['j_fabricRL1'] = 'FabricR01_L'
names['j_fabricRL2'] = 'FabricR02_L'
names['j_fabricRL3'] = 'FabricR03_L'

names['j_fabricRR1'] = 'FabricR1_R'
names['j_fabricRR2'] = 'FabricR2_R'
names['j_fabricRR3'] = 'FabricR3_R'

names['j_fabric03']  = 'Fabric_L'
names['j_fabric01']  = 'Fabric_R'
names['j_fabric04']  = 'Fabric_F'
names['j_fabric02']  = 'Fabric_B'
 
names['j_mantle01']  = 'Mantle01'
names['j_mantle02']  = 'Mantle02'
names['j_mantle03']  = 'Mantle03'
names['j_mantle04']  = 'Mantle04'
names['j_mantle05']  = 'Mantle05'
names['j_mantle06']  = 'Mantle06'
names['j_mantle07']  = 'Mantle07'
names['j_mantle08']  = 'Mantle08'

names['j_mantle01_l'] = 'Mantle01_L'
names['j_mantle02_l'] = 'Mantle02_L'
names['j_mantle03_l'] = 'Mantle03_L'
names['j_mantle04_l'] = 'Mantle04_L'
names['j_mantle05_l'] = 'Mantle05_L'
names['j_mantle06_l'] = 'Mantle06_L'
names['j_mantle07_l'] = 'Mantle07_L'
names['j_mantle08_l'] = 'Mantle08_L'
names['j_mantle01_r'] = 'Mantle01_R'
names['j_mantle02_r'] = 'Mantle02_R'
names['j_mantle03_r'] = 'Mantle03_R'
names['j_mantle04_r'] = 'Mantle04_R'
names['j_mantle05_r'] = 'Mantle05_R'
names['j_mantle06_r'] = 'Mantle06_R'
names['j_mantle07_r'] = 'Mantle07_R'
names['j_mantle08_r'] = 'Mantle08_R'

names['j_l_u_sk01']   = 'Skirt01_U_L'
names['j_l_u_sk01']   = 'Skirt01_U_R'
names['j_l_u_sk01']   = 'Skirt01_D_L'
names['j_l_u_sk01']   = 'Skirt01_D_R'

names['j_l_sk0']  = 'Skirt0_L'
names['j_r_sk0']  = 'Skirt0_R'
names['j_l_sk01'] = 'Skirt01_L'
names['j_r_sk01'] = 'Skirt01_R'
names['j_l_sk02'] = 'Skirt02_L'
names['j_r_sk02'] = 'Skirt02_R'
names['j_l_sk03'] = 'Skirt03_L'
names['j_r_sk03'] = 'Skirt03_R'
names['j_l_sk04'] = 'Skirt04_L'
names['j_r_sk04'] = 'Skirt04_R'
names['j_l_sk05'] = 'Skirt05_L'
names['j_r_sk05'] = 'Skirt05_R'

names['j_l_sk1']  = 'Skirt1_L'
names['j_r_sk1']  = 'Skirt1_R'
names['j_l_sk11'] = 'Skirt11_L'
names['j_r_sk11'] = 'Skirt11_R'
names['j_l_sk12'] = 'Skirt12_L'
names['j_r_sk12'] = 'Skirt12_R'
names['j_l_sk13'] = 'Skirt13_L'
names['j_r_sk13'] = 'Skirt13_R'
names['j_l_sk14'] = 'Skirt14_L'
names['j_r_sk14'] = 'Skirt14_R'
names['j_l_sk15'] = 'Skirt15_L'
names['j_r_sk15'] = 'Skirt15_R'
names['j_l_sk2']  = 'Skirt2_L'
names['j_r_sk2']  = 'Skirt2_R'
names['j_l_sk21'] = 'Skirt21_L'
names['j_r_sk21'] = 'Skirt21_R'
names['j_l_sk22'] = 'Skirt22_L'
names['j_r_sk22'] = 'Skirt22_R'
names['j_l_sk23'] = 'Skirt23_L'
names['j_r_sk23'] = 'Skirt23_R'
names['j_l_sk24'] = 'Skirt24_L'
names['j_r_sk24'] = 'Skirt24_R'
names['j_l_sk25'] = 'Skirt25_L'
names['j_r_sk25'] = 'Skirt25_R'

names['j_l_u_sk0']  = 'Skirt0_U_L'
names['j_r_u_sk0']  = 'Skirt0_U_R'
names['j_l_u_sk01'] = 'Skirt01_U_L'
names['j_r_u_sk01'] = 'Skirt01_U_R'
names['j_l_u_sk02'] = 'Skirt02_U_L'
names['j_r_u_sk02'] = 'Skirt02_U_R'
names['j_l_u_sk03'] = 'Skirt03_U_L'
names['j_r_u_sk03'] = 'Skirt03_U_R'

names['j_l_u_sk1']  = 'Skirt1_U_L'
names['j_r_u_sk1']  = 'Skirt1_U_R'
names['j_l_u_sk11'] = 'Skirt11_U_L'
names['j_r_u_sk11'] = 'Skirt11_U_R'
names['j_l_u_sk12'] = 'Skirt12_U_L'
names['j_r_u_sk12'] = 'Skirt12_U_R'
names['j_l_u_sk13'] = 'Skirt13_U_L'
names['j_r_u_sk13'] = 'Skirt13_U_R'

names['j_l_u_sk2']  = 'Skirt2_U_L'
names['j_r_u_sk2']  = 'Skirt2_U_R'
names['j_l_u_sk21'] = 'Skirt21_U_L'
names['j_r_u_sk21'] = 'Skirt21_U_R'
names['j_l_u_sk22'] = 'Skirt22_U_L'
names['j_r_u_sk22'] = 'Skirt22_U_R'
names['j_l_u_sk23'] = 'Skirt23_U_L'
names['j_r_u_sk23'] = 'Skirt23_U_R'

names['j_f_sk01']   = 'Skirt01_F'
names['j_b_sk01']   = 'Skirt01_B'

names['j_b_sk01']   = 'Skirt01_B'
names['j_b_sk02']   = 'Skirt02_B'
names['j_b_sk03']   = 'Skirt03_B'

names['j_skirt01_b'] = 'Skirt01_B'
names['j_skirt02_b'] = 'Skirt02_B'
names['j_skirt03_b'] = 'Skirt03_B'
names['j_skirt04_b'] = 'Skirt04_B'
names['j_skirt05_b'] = 'Skirt05_B'
names['j_skirt06_b'] = 'Skirt06_B'
names['j_skirt01_f'] = 'Skirt01_F'
names['j_skirt02_f'] = 'Skirt02_F'
names['j_skirt03_f'] = 'Skirt03_F'
names['j_skirt04_f'] = 'Skirt04_F'
names['j_skirt05_f'] = 'Skirt05_F'
names['j_skirt06_f'] = 'Skirt06_F'
names['j_skirt01_l'] = 'Skirt01_L'
names['j_skirt02_l'] = 'Skirt02_L'
names['j_skirt03_l'] = 'Skirt03_L'
names['j_skirt04_l'] = 'Skirt04_L'
names['j_skirt05_l'] = 'Skirt05_L'
names['j_skirt06_l'] = 'Skirt06_L'
names['j_skirt01_r'] = 'Skirt01_R'
names['j_skirt02_r'] = 'Skirt02_R'
names['j_skirt03_r'] = 'Skirt03_R'
names['j_skirt04_r'] = 'Skirt04_R'
names['j_skirt05_r'] = 'Skirt05_R'
names['j_skirt06_r'] = 'Skirt06_R'

# Dedos simplificados
names['j_handL'] = 'Fingers_L'
names['j_handR'] = 'Fingers_R'

# Rosto
names['j_mouth']   = 'Mouth'
names['j_jaw']     = 'Jaw'
names['j_joe']     = 'Joe'
names['j_l_mouth'] = 'Mouth_L'
names['j_r_mouth'] = 'Mouth_R'
names['j_u_mouth'] = 'Mouth_U'
names['j_d_mouth'] = 'Mouth_D'

# Lingua
names['tongue']     = 'Tongue'
names['tongue0']    = 'Tongue0'
names['tongue01']   = 'Tongue01'
names['tongue1']    = 'Tongue1'
names['tongue11']   = 'Tongue11'
names['tongue12']   = 'Tongue12'
names['j_tongue']   = 'Tongue'
names['j_tongue0']  = 'Tongue0'
names['j_tongue01'] = 'Tongue01'
names['j_tongue1']  = 'Tongue1'
names['j_tongue11'] = 'Tongue11'
names['j_tongue12'] = 'Tongue12'

# Cauda
names['j_tail']   = 'Tail'
names['j_tail01'] = 'Tail01'
names['j_tail02'] = 'Tail02'
names['j_tail03'] = 'Tail03'
names['j_tail04'] = 'Tail04'
names['j_tail05'] = 'Tail05'

names['j_tail1'] = 'Tail01'
names['j_tail2'] = 'Tail02'
names['j_tail3'] = 'Tail03'
names['j_tail4'] = 'Tail04'
names['j_tail5'] = 'Tail05'

# Orelhas
names['j_l_ear']   = 'Ear_L'
names['j_r_ear']   = 'Ear_R'
names['j_l_ear01'] = 'Ear01_L'
names['j_r_ear01'] = 'Ear01_R'
names['j_l_ear02'] = 'Ear02_L'
names['j_r_ear02'] = 'Ear02_R'

names['j_ear01_l'] = 'Ear01_L'
names['j_ear01_r'] = 'Ear01_R'
names['j_ear02_l'] = 'Ear02_L'
names['j_ear02_r'] = 'Ear02_R'
names['j_ear03_l'] = 'Ear03_L'
names['j_ear03_r'] = 'Ear03_R'
names['j_ear04_l'] = 'Ear04_L'
names['j_ear04_r'] = 'Ear04_R'
names['j_ear05_l'] = 'Ear05_L'
names['j_ear05_r'] = 'Ear05_R'
names['j_ear06_l'] = 'Ear06_L'
names['j_ear06_r'] = 'Ear06_R'
names['j_ear07_l'] = 'Ear07_L'
names['j_ear07_r'] = 'Ear07_R'

# Bigodes
names['j_l_whisker'] = 'Whisker_L'
names['j_r_whisker'] = 'Whisker_R'

# Cabelos
names['j_l_osage']   = 'Osage_L'
names['j_r_osage']   = 'Osage_R'
names['j_l_osage0']  = 'Osage0_L'
names['j_r_osage0']  = 'Osage0_R'
names['j_r_osage01'] = 'Hair01_R'
names['j_l_osage02'] = 'Hair02_L'
names['j_r_osage03'] = 'Hair02_R'
names['j_l_osage04'] = 'Hair03_L'
names['j_r_osage05'] = 'Hair03_R'
names['j_l_osage06'] = 'Hair04_L'
names['j_r_osage07'] = 'Hair04_R'
names['j_l_osage08'] = 'Hair05_L'
names['j_r_osage09'] = 'Hair05_R'

names['j_l_hair01'] = 'Hair1_L'
names['j_r_hair01'] = 'Hair1_R'
names['j_l_hair02'] = 'Hair2_L'
names['j_r_hair02'] = 'Hair2_R'
names['j_l_hair03'] = 'Hair3_L'
names['j_r_hair03'] = 'Hair3_R'

names['j_l_sidehair']   = 'Hair_L'
names['j_r_sidehair']   = 'Hair_R'
names['j_l_sidehair01'] = 'Hair11_L'
names['j_r_sidehair01'] = 'Hair11_R'
names['j_l_sidehair02'] = 'Hair12_L'
names['j_r_sidehair02'] = 'Hair12_R'

# Asas
names['j_l_u_wing0']  = 'Wing0_L'
names['j_r_u_wing0']  = 'Wing0_R'
names['j_l_u_wing01'] = 'Wing01_L'
names['j_r_u_wing01'] = 'Wing01_R'
names['j_l_u_wing02'] = 'Wing02_L'
names['j_r_u_wing02'] = 'Wing02_R'
names['j_l_u_wing03'] = 'Wing03_L'
names['j_r_u_wing03'] = 'Wing03_R'
names['j_l_u_wing04'] = 'Wing04_L'
names['j_r_u_wing04'] = 'Wing04_R'
names['j_l_u_wing05'] = 'Wing05_L'
names['j_r_u_wing05'] = 'Wing05_R'
names['j_l_u_wing06'] = 'Wing06_L'
names['j_r_u_wing06'] = 'Wing06_R'
names['j_l_u_wing1']  = 'Wing1_L'
names['j_r_u_wing1']  = 'Wing1_R'
names['j_l_u_wing11'] = 'Wing11_L'
names['j_r_u_wing11'] = 'Wing11_R'
names['j_l_u_wing12'] = 'Wing12_L'
names['j_r_u_wing12'] = 'Wing12_R'
names['j_l_u_wing13'] = 'Wing13_L'
names['j_r_u_wing13'] = 'Wing13_R'
names['j_l_u_wing14'] = 'Wing14_L'
names['j_r_u_wing14'] = 'Wing14_R'
names['j_l_u_wing15'] = 'Wing15_L'
names['j_r_u_wing15'] = 'Wing15_R'
names['j_l_u_wing16'] = 'Wing16_L'
names['j_r_u_wing16'] = 'Wing16_R'
names['j_l_u_wing2']  = 'Wing2_L'
names['j_r_u_wing2']  = 'Wing2_R'
names['j_l_u_wing21'] = 'Wing21_L'
names['j_r_u_wing21'] = 'Wing21_R'
names['j_l_u_wing22'] = 'Wing22_L'
names['j_r_u_wing22'] = 'Wing22_R'
names['j_l_u_wing23'] = 'Wing23_L'
names['j_r_u_wing23'] = 'Wing23_R'
names['j_l_u_wing24'] = 'Wing24_L'
names['j_r_u_wing24'] = 'Wing24_R'
names['j_l_u_wing25'] = 'Wing25_L'
names['j_r_u_wing25'] = 'Wing25_R'
names['j_l_u_wing26'] = 'Wing26_L'
names['j_r_u_wing26'] = 'Wing26_R'
names['j_l_u_wing3']  = 'Wing3_L'
names['j_r_u_wing3']  = 'Wing3_R'
names['j_l_u_wing31'] = 'Wing31_L'
names['j_r_u_wing31'] = 'Wing31_R'
names['j_l_u_wing32'] = 'Wing32_L'
names['j_r_u_wing32'] = 'Wing32_R'
names['j_l_u_wing33'] = 'Wing33_L'
names['j_r_u_wing33'] = 'Wing33_R'
names['j_l_u_wing34'] = 'Wing34_L'
names['j_r_u_wing34'] = 'Wing34_R'
names['j_l_u_wing35'] = 'Wing35_L'
names['j_r_u_wing35'] = 'Wing35_R'
names['j_l_u_wing36'] = 'Wing36_L'
names['j_r_u_wing36'] = 'Wing36_R'
names['j_l_u_wing4']  = 'Wing4_L'
names['j_r_u_wing4']  = 'Wing4_R'
names['j_l_u_wing41'] = 'Wing41_L'
names['j_r_u_wing41'] = 'Wing41_R'
names['j_l_u_wing42'] = 'Wing42_L'
names['j_r_u_wing42'] = 'Wing42_R'
names['j_l_u_wing43'] = 'Wing43_L'
names['j_r_u_wing43'] = 'Wing43_R'
names['j_l_u_wing44'] = 'Wing44_L'
names['j_r_u_wing44'] = 'Wing44_R'
names['j_l_u_wing45'] = 'Wing45_L'
names['j_r_u_wing45'] = 'Wing45_R'
names['j_l_u_wing46'] = 'Wing46_L'
names['j_r_u_wing46'] = 'Wing46_R'
names['j_l_u_wing5']  = 'Wing5_L'
names['j_r_u_wing5']  = 'Wing5_R'
names['j_l_u_wing51'] = 'Wing51_L'
names['j_r_u_wing51'] = 'Wing51_R'
names['j_l_u_wing52'] = 'Wing52_L'
names['j_r_u_wing52'] = 'Wing52_R'
names['j_l_u_wing53'] = 'Wing53_L'
names['j_r_u_wing53'] = 'Wing53_R'
names['j_l_u_wing54'] = 'Wing54_L'
names['j_r_u_wing54'] = 'Wing54_R'
names['j_l_u_wing55'] = 'Wing55_L'
names['j_r_u_wing55'] = 'Wing55_R'
names['j_l_u_wing56'] = 'Wing56_L'
names['j_r_u_wing56'] = 'Wing56_R'

names['j_wing0_l']  = 'Wing0_L'
names['j_wing0_r']  = 'Wing0_R'
names['j_wing01_l'] = 'Wing01_L'
names['j_wing01_r'] = 'Wing01_R'
names['j_wing02_l'] = 'Wing02_L'
names['j_wing02_r'] = 'Wing02_R'
names['j_wing03_l'] = 'Wing03_L'
names['j_wing03_r'] = 'Wing03_R'
names['j_wing04_l'] = 'Wing04_L'
names['j_wing04_r'] = 'Wing04_R'
names['j_wing05_l'] = 'Wing05_L'
names['j_wing05_r'] = 'Wing05_R'
names['j_wing06_l'] = 'Wing06_L'
names['j_wing06_r'] = 'Wing06_R'

names['j_wing0_a_l']  = 'Wing0_A_L'
names['j_wing0_a_r']  = 'Wing0_A_R'
names['j_wing01_a_l'] = 'Wing01_A_L'
names['j_wing01_a_r'] = 'Wing01_A_R'
names['j_wing02_a_l'] = 'Wing02_A_L'
names['j_wing02_a_r'] = 'Wing02_A_R'
names['j_wing03_a_l'] = 'Wing03_A_L'
names['j_wing03_a_r'] = 'Wing03_A_R'
names['j_wing04_a_l'] = 'Wing04_A_L'
names['j_wing04_a_r'] = 'Wing04_A_R'
names['j_wing05_a_l'] = 'Wing05_A_L'
names['j_wing05_a_r'] = 'Wing05_A_R'
names['j_wing06_a_l'] = 'Wing06_A_L'
names['j_wing06_a_r'] = 'Wing06_A_R'

names['j_wing0_b_l']  = 'Wing0_B_L'
names['j_wing0_b_r']  = 'Wing0_B_R'
names['j_wing01_b_l'] = 'Wing01_B_L'
names['j_wing01_b_r'] = 'Wing01_B_R'
names['j_wing02_b_l'] = 'Wing02_B_L'
names['j_wing02_b_r'] = 'Wing02_B_R'
names['j_wing03_b_l'] = 'Wing03_B_L'
names['j_wing03_b_r'] = 'Wing03_B_R'
names['j_wing04_b_l'] = 'Wing04_B_L'
names['j_wing04_b_r'] = 'Wing04_B_R'
names['j_wing05_b_l'] = 'Wing05_B_L'
names['j_wing05_b_r'] = 'Wing05_B_R'
names['j_wing06_b_l'] = 'Wing06_B_L'
names['j_wing06_b_r'] = 'Wing06_B_R'

names['j_l_d_wing0']  = 'Wing0_D_L'
names['j_r_d_wing0']  = 'Wing0_D_R'
names['j_l_d_wing01'] = 'Wing01_D_L'
names['j_r_d_wing01'] = 'Wing01_D_R'
names['j_l_d_wing02'] = 'Wing02_D_L'
names['j_r_d_wing02'] = 'Wing02_D_R'
names['j_l_d_wing03'] = 'Wing03_D_L'
names['j_r_d_wing03'] = 'Wing03_D_R'
names['j_l_d_wing04'] = 'Wing04_D_L'
names['j_r_d_wing04'] = 'Wing04_D_R'
names['j_l_d_wing05'] = 'Wing05_D_L'
names['j_r_d_wing05'] = 'Wing05_D_R'
names['j_l_d_wing06'] = 'Wing06_D_L'
names['j_r_d_wing06'] = 'Wing06_D_R'

# Antenas
names['j_l_antenna']   = 'Antenna_L'
names['j_r_antenna']   = 'Antenna_R'
names['j_l_antenna0']  = 'Antenna0_L'
names['j_r_antenna0']  = 'Antenna0_R'
names['j_l_antenna01'] = 'Antenna01_L'
names['j_r_antenna01'] = 'Antenna01_R'
names['j_l_antenna02'] = 'Antenna02_L'
names['j_r_antenna02'] = 'Antenna02_R'
names['j_l_antenna03'] = 'Antenna03_L'
names['j_r_antenna03'] = 'Antenna03_R'
names['j_l_antenna1']  = 'Antenna1_L'
names['j_r_antenna1']  = 'Antenna1_R'
names['j_l_antenna11'] = 'Antenna11_L'
names['j_r_antenna11'] = 'Antenna11_R'
names['j_l_antenna12'] = 'Antenna12_L'
names['j_r_antenna12'] = 'Antenna12_R'
names['j_l_antenna13'] = 'Antenna13_L'
names['j_r_antenna13'] = 'Antenna13_R'
names['j_l_antenna2']  = 'Antenna2_L'
names['j_r_antenna2']  = 'Antenna2_R'
names['j_l_antenna21'] = 'Antenna21_L'
names['j_r_antenna21'] = 'Antenna21_R'
names['j_l_antenna22'] = 'Antenna22_L'
names['j_r_antenna22'] = 'Antenna22_R'
names['j_l_antenna23'] = 'Antenna23_L'
names['j_r_antenna23'] = 'Antenna23_R'

# Props
names['j_ring']    = 'Ring'
names['j_shield']  = 'Shield'
names['j_sword']   = 'Sword'
names['j_sword_l'] = 'Sword_L'
names['j_sword_r'] = 'Sword_R'

names['j_weapon_root_l'] = 'Weapon_root_L'
names['j_weapon_root_r'] = 'Weapon_root_R'

names['j_far0_c']  = 'Far0_C'
names['j_far00_c'] = 'Far00_C'
names['j_far01_c'] = 'Far01_C'
names['j_far02_c'] = 'Far02_C'
names['j_far03_c'] = 'Far03_C'
names['j_far04_c'] = 'Far04_C'
names['j_far1_c']  = 'Far1_C'
names['j_far10_c'] = 'Fae10_C'
names['j_far11_c'] = 'Far11_C'
names['j_far12_c'] = 'Far12_C'
names['j_far13_c'] = 'Far13_C'
names['j_far14_c'] = 'Far14_C'

# Sistermon's veil
names['j_l_veil01'] = 'veil01_l'
names['j_l_veil02'] = 'veil02_l'
names['j_l_veil03'] = 'veil03_l'
names['j_l_veil04'] = 'veil04_l'
names['j_l_veil05'] = 'veil05_l'
names['j_r_veil01'] = 'veil01_r'
names['j_r_veil02'] = 'veil02_r'
names['j_r_veil03'] = 'veil03_r'
names['j_r_veil04'] = 'veil04_r'
names['j_r_veil05'] = 'veil05_r'
names['j_b_veil01'] = 'veil01_b'
names['j_b_veil02'] = 'veil02_b'
names['j_b_veil03'] = 'veil03_b'
names['j_b_veil04'] = 'veil04_b'
names['j_b_veil05'] = 'veil05_b'

