
# Purpose: select an armature on a human model imported form Left 4 Dead, Garry's Mode, Half-Life 2
# run this script, all bones renamed to their Blender counterparts

names = dict()

# Purpose: select an armature from a ValveBiped model
# run this
# Get a Blender style armature

names['ValveBiped.Bip01_Pelvis'] = 'Pelvis'
names['ValveBiped.Bip01_Spine']  = 'Spine'
names['ValveBiped.Bip01_Spine0'] = 'Spine0'
names['ValveBiped.Bip01_Spine1'] = 'Spine1'
names['ValveBiped.Bip01_Spine2'] = 'Spine2'
names['ValveBiped.Bip01_Spine3'] = 'Spine3'
names['ValveBiped.Bip01_Spine4'] = 'Spine4'

names['ValveBiped.Bip01_Neck1'] = 'Neck1'
names['ValveBiped.Bip01_Head1'] = 'Head1'

names['ValveBiped.Bip01_R_Hip']       = 'Helper_Hip_R'
names['ValveBiped.Bip01_L_Hip']       = 'Helper_Hip_L'
names['ValveBiped.Bip01_R_Glute']     = 'Helper_Glute_R'
names['ValveBiped.Bip01_L_Glute']     = 'Helper_Glute_L'
names['ValveBiped.Bip01_R_Sartorius'] = 'Helper_Sartorius_R'
names['ValveBiped.Bip01_L_Sartorius'] = 'Helper_Sartorius_L'
names['ValveBiped.Bip01_R_Thigh']     = 'Thigh_R'
names['ValveBiped.Bip01_L_Thigh']     = 'Thigh_L'
names['ValveBiped.Bip01_R_Quadricep'] = 'Helper_Quadricep_R'
names['ValveBiped.Bip01_L_Quadricep'] = 'Helper_Quadricep_L'
names['ValveBiped.Bip01_R_Quad']      = 'Helper_Quad_R'
names['ValveBiped.Bip01_L_Quad']      = 'Helper_Quad_L'
names['ValveBiped.Bip01_R_Knee']      = 'Helper_Knee_R'
names['ValveBiped.Bip01_L_Knee']      = 'Helper_Knee_L'
names['ValveBiped.Bip01_R_Calf']      = 'Calf_R'
names['ValveBiped.Bip01_L_Calf']      = 'Calf_L'
names['ValveBiped.Bip01_R_Shin']      = 'Helper_Shin_R'
names['ValveBiped.Bip01_L_Shin']      = 'Helper_Shin_L'
names['ValveBiped.Bip01_R_Soleus']    = 'Helper_Soleus_R'
names['ValveBiped.Bip01_L_Soleus']    = 'Helper_Soleus_L'
names['ValveBiped.Bip01_R_Ankle']     = 'Helper_Ankle_R'
names['ValveBiped.Bip01_L_Ankle']     = 'Helper_Ankle_L'
names['ValveBiped.Bip01_R_Foot']      = 'Foot_R'
names['ValveBiped.Bip01_L_Foot']      = 'Foot_L'
names['ValveBiped.Bip01_R_Toe0']      = 'Toe0_R'
names['ValveBiped.Bip01_L_Toe0']      = 'Toe0_L'

names['ValveBiped.Bip01_R_Pectoral']  = 'Helper_Pectoral_R'
names['ValveBiped.Bip01_L_Pectoral']  = 'Helper_Pectoral_L'
names['ValveBiped.Bip01_R_Latt']      = 'Helper_Latt_R'
names['ValveBiped.Bip01_L_Latt']      = 'Helper_Latt_L'
names['ValveBiped.Bip01_R_Trapezius'] = 'Helper_Trapezius_R'
names['ValveBiped.Bip01_L_Trapezius'] = 'Helper_Trapezius_L'
names['ValveBiped.Bip01_R_Clavicle']  = 'Clavicle_R'
names['ValveBiped.Bip01_L_Clavicle']  = 'Clavicle_L'
names['ValveBiped.Bip01_R_Shoulder']  = 'Helper_Shoulder_R'
names['ValveBiped.Bip01_L_Shoulder']  = 'Helper_Shoulder_L'
names['ValveBiped.Bip01_R_Bicep']     = 'Helper_Bicep_R'
names['ValveBiped.Bip01_L_Bicep']     = 'Helper_Bicep_L'
names['ValveBiped.Bip01_R_UpperArm']  = 'UpperArm_R'
names['ValveBiped.Bip01_L_UpperArm']  = 'UpperArm_L'
names['ValveBiped.Bip01_R_Elbow']     = 'Helper_Elbow_R'
names['ValveBiped.Bip01_L_Elbow']     = 'Helper_Elbow_L'
names['ValveBiped.Bip01_R_Forearm']   = 'Forearm_R'
names['ValveBiped.Bip01_L_Forearm']   = 'Forearm_L'
names['ValveBiped.Bip01_R_Ulna']      = 'Helper_Ulna_R'
names['ValveBiped.Bip01_L_Ulna']      = 'Helper_Ulna_L'
names['ValveBiped.Bip01_R_Wrist']     = 'Helper_Wrist_R'
names['ValveBiped.Bip01_L_Wrist']     = 'Helper_Wrist_L'
names['ValveBiped.Bip01_R_Hand']      = 'Hand_R'
names['ValveBiped.Bip01_L_Hand']      = 'Hand_L'

names['ValveBiped.Bip01_R_Finger0']  = 'Finger0_R'
names['ValveBiped.Bip01_L_Finger0']  = 'Finger0_L'
names['ValveBiped.Bip01_R_Finger01'] = 'Finger01_R'
names['ValveBiped.Bip01_L_Finger01'] = 'Finger01_L'
names['ValveBiped.Bip01_R_Finger02'] = 'Finger02_R'
names['ValveBiped.Bip01_L_Finger02'] = 'Finger02_L'

names['ValveBiped.Bip01_R_Finger1']  = 'Finger1_R'
names['ValveBiped.Bip01_L_Finger1']  = 'Finger1_L'
names['ValveBiped.Bip01_R_Finger11'] = 'Finger11_R'
names['ValveBiped.Bip01_L_Finger11'] = 'Finger11_L'
names['ValveBiped.Bip01_R_Finger12'] = 'Finger12_R'
names['ValveBiped.Bip01_L_Finger12'] = 'Finger12_L'

names['ValveBiped.Bip01_R_Finger2']  = 'Finger2_R'
names['ValveBiped.Bip01_L_Finger2']  = 'Finger2_L'
names['ValveBiped.Bip01_R_Finger21'] = 'Finger21_R'
names['ValveBiped.Bip01_L_Finger21'] = 'Finger21_L'
names['ValveBiped.Bip01_R_Finger22'] = 'Finger22_R'
names['ValveBiped.Bip01_L_Finger22'] = 'Finger22_L'

names['ValveBiped.Bip01_R_Finger3']  = 'Finger3_R'
names['ValveBiped.Bip01_L_Finger3']  = 'Finger3_L'
names['ValveBiped.Bip01_R_Finger31'] = 'Finger31_R'
names['ValveBiped.Bip01_L_Finger31'] = 'Finger31_L'
names['ValveBiped.Bip01_R_Finger32'] = 'Finger32_R'
names['ValveBiped.Bip01_L_Finger32'] = 'Finger32_L'

names['ValveBiped.Bip01_R_Finger4']  = 'Finger4_R'
names['ValveBiped.Bip01_L_Finger4']  = 'Finger4_L'
names['ValveBiped.Bip01_R_Finger41'] = 'Finger41_R'
names['ValveBiped.Bip01_L_Finger41'] = 'Finger41_L'
names['ValveBiped.Bip01_R_Finger42'] = 'Finger42_R'
names['ValveBiped.Bip01_L_Finger42'] = 'Finger42_L'

names['weapon_bone_L'] = 'weapon_bone_L'
names['weapon_bone']   = 'weapon_bone_R'

